## 应用名称
#spring.application.name=demo
#
## 应用服务 WEB 访问端口
#server.port=8080
## spring 静态资源扫描路径
#spring.resources.static-locations=classpath:/static/
#
#

server:
  port: 8090

netty:
  port: 8080
  host: 127.0.0.1
